Repository ssi-dk/SCDB, pull requests merged in 2023-09, with the labels that each got.

#21 Add option to suppress Logger output
  R/Logger.R
  man/Logger.Rd
  tests/testthat/test-Logger.R
Labels: enhancement

#26 Warn user when connecting with a backend not fully supported
  R/connection.R
  man/get_connection.Rd
Labels: enhancement

#30 Detect schema without tables in schema_exists
  R/get_schema.R
Labels: bug

#31 test: add postgres service to test-coverage
  .github/workflows/test-coverage.yaml
Labels: enhancement

#39 Build README with Rmarkdown
  .github/workflows/render-readme.yaml
  README.Rmd
  README.md
Labels: documentation, enhancement

#43 Various fixes to the pkgdown site
  .Rbuildignore
  .gitignore
  NEWS.md
  vignettes/basic_principles.Rmd
Labels: documentation

#51 docs: remove db_timestamp.NULL from reference
  R/db_timestamps.R
  man/db_timestamp.Rd
Labels: documentation
