Repository ssi-dk/SCDB, pull requests merged in 2024-02, with the labels that each got.

#100 Informative error message for `id.tbl_dbi`
  R/id.R
  tests/testthat/test-id.R
Labels: bug

#97 Improve `digest_to_checksum` for SQL Server
  NAMESPACE
  NEWS.md
  R/SCDB-package.R
  R/digest_to_checksum.R
  R/getTableSignature.R
  R/unite.tbl_dbi.R
  R/update_snapshot.R
  inst/WORDLIST
  man/digest_to_checksum.Rd
  tests/testthat/test-digest_to_checksum.R
  tests/testthat/test-update_snapshot.R
Labels: enhancement

#99 Add catalog information
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/get_catalog.R
  R/get_schema.R
  R/id.R
  inst/WORDLIST
  man/SCDB-package.Rd
  man/get_schema.Rd
  tests/testthat/test-get_schema.R
Labels: enhancement

#89 Delete intermediate tables after use
  NAMESPACE
  NEWS.md
  R/Logger.R
  R/digest_to_checksum.R
  R/helpers.R
  R/interlace_sql.R
  R/update_snapshot.R
  man/defer_db_cleanup.Rd
  man/unique_table_name.Rd
  tests/testthat/setup.R
  tests/testthat/test-Logger.R
  tests/testthat/test-connection.R
  tests/testthat/test-create_logs_if_missing.R
  tests/testthat/test-create_table.R
  tests/testthat/test-db_functions.R
  tests/testthat/test-db_joins.R
  tests/testthat/test-db_timestamp.R
  tests/testthat/test-digest_to_checksum.R
  tests/testthat/test-filter_keys.R
  tests/testthat/test-get_table.R
  tests/testthat/test-get_tables.R
  tests/testthat/test-helpers.R
  tests/testthat/test-id.R
  tests/testthat/test-interlace_sql.R
  tests/testthat/test-schema_exists.R
  tests/testthat/test-slice_time.R
  tests/testthat/test-table_exists.R
  tests/testthat/test-unite.tbl_dbi.R
  tests/testthat/test-update_snapshot.R
  tests/testthat/test-zzz.R
Labels: enhancement

#105 Update description
  DESCRIPTION
  man/SCDB-package.Rd
Labels: documentation

#98 `Logger` overhaul
  NAMESPACE
  NEWS.md
  R/Logger.R
  R/table_exists.R
  R/update_snapshot.R
  inst/WORDLIST
  man/Logger.Rd
  man/LoggerNull.Rd
  pak.lock
  tests/testthat/setup.R
  tests/testthat/test-Logger.R
  tests/testthat/test-update_snapshot.R
  vignettes/basic-principles.Rmd
Labels: enhancement

#107 Support temporary schemas in `get_schema()`
  NEWS.md
  R/get_catalog.R
  R/get_schema.R
  R/get_tables.R
  R/helpers.R
  R/id.R
  R/table_exists.R
  inst/WORDLIST
  man/defer_db_cleanup.Rd
  man/get_schema.Rd
  man/id.Rd
  tests/testthat/test-create_logs_if_missing.R
  tests/testthat/test-get_schema.R
  tests/testthat/test-get_table.R
  tests/testthat/test-helpers.R
  tests/testthat/test-id.R
Labels: enhancement

#106 Only create, don't write, tables with `create_table`
  R/create_table.R
  tests/testthat/test-create_table.R
Labels: bug

#104 Add a db lock system to prevent race conditions
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/helpers.R
  R/locks.R
  R/update_snapshot.R
  inst/WORDLIST
  man/db_locks.Rd
  pak.lock
  tests/testthat/test-locks.R
Labels: enhancement

#109 Add `...` args to `filter_keys()`
  R/filter_keys.R
  man/filter_keys.Rd
  tests/testthat/test-filter_keys.R
Labels: enhancement

#101 chore: synced file(s) with ssi-dk/AEF-DDF
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/sync_reverse.yaml
  .github/templates/README_template.Rmd
  .github/workflows/synchronise-files.yaml
  README.Rmd
  README.md
  tests/testthat/test-0_rd_files.R
Labels: sync

#116 chore: synced file(s) with ssi-dk/AEF-DDF
  .github/workflows/synchronise-files.yaml
Labels: sync

#117 chore: synced file(s) with ssi-dk/AEF-DDF
  .github/workflows/synchronise-files.yaml
Labels: sync

#120 chore: synced file(s) with ssi-dk/AEF-DDF
  tests/testthat/helper-setup.R
Labels: sync

#121 Add support for DuckDB
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/connection.R
  R/db_timestamps.R
  R/digest_to_checksum.R
  R/getTableSignature.R
  R/get_catalog.R
  R/get_schema.R
  R/get_tables.R
  inst/WORDLIST
  man/get_connection.Rd
  tests/testthat/helper-setup.R
  tests/testthat/setup.R
  tests/testthat/test-connection.R
  tests/testthat/test-getTableSignature.R
  tests/testthat/test-interlace.R
Labels: enhancement
