Repository ssi-dk/SCDB, pull requests merged in 2024-01, with the labels that each got.

#77 feat: Add support for Microsoft SQL Server (MSSQL)
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/SCDB-package.R
  R/create_table.R
  R/db_joins.R
  R/db_manipulating_functions.R
  R/digest_to_checksum.R
  R/get_schema.R
  R/get_table.R
  R/update_snapshot.R
  inst/WORDLIST
  man/joins.Rd
  man/table_exists.Rd
  tests/testthat/setup.R
  tests/testthat/test-connection.R
  tests/testthat/test-db_joins.R
  tests/testthat/test-update_snapshot.R
Labels: enhancement

#83 feat: Better checks in `get_connection`
  NEWS.md
  R/connection.R
  man/get_connection.Rd
Labels: enhancement

#80 Improve CI tests
  .github/workflows/R-CMD-check.yaml
  .github/workflows/all-workflows.yaml
  .github/workflows/document.yaml
  .github/workflows/lint.yaml
  .github/workflows/pkgdown.yaml
  .github/workflows/r-license-report.yaml
  .github/workflows/render-readme.yaml
  .github/workflows/test-coverage.yaml
  DESCRIPTION
  R/get_table.R
  tests/testthat/helper-setup.R
  tests/testthat/setup.R
  tests/testthat/test-Logger.R
  tests/testthat/test-connection.R
  tests/testthat/test-db_functions.R
  tests/testthat/test-db_joins.R
  tests/testthat/test-db_manipulating_functions.R
  tests/testthat/test-db_timestamp.R
  tests/testthat/test-get_schema.R
  tests/testthat/test-get_table.R
  tests/testthat/test-helpers.R
  tests/testthat/test-update_snapshot.R
  tests/testthat/test-zzz.R
  vignettes/basic-principles.Rmd
Labels: enhancement

#81 Add website to DESCRIPTION
  DESCRIPTION
Labels: documentation

#87 chore: synced file(s) with ssi-dk/AEF-DDF
  .github/workflows/all-workflows.yaml
  tests/testthat/helper-setup.R
Labels: sync

#91 chore: synced file(s) with ssi-dk/AEF-DDF
  tests/testthat/helper-setup.R
Labels: sync
